FROM node:18-alpine 
WORKDIR /app 
COPY server/package.json . 
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
COPY . .
EXPOSE 7000
CMD ["node", "server/main.js"]

